{
 "title": "New dashboard",
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  prediction_drift\nFROM drift_metrics\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  share_missing_values\nFROM drift_metrics\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  num_drifted_columns\nFROM drift_metrics\nORDER BY 1"
    }
   ]
  }
 ]
}